return {
  { 'wbthomason/packer.nvim' },
  { 'nvim-lua/plenary.nvim' },
  { 'rcarriga/nvim-notify', name = 'notify' },
  { 'shurizzle/inlay-hints.nvim', name = 'inlayhints' },
  {
    'neovim/nvim-lspconfig',
    name = 'lsp',
  },
  {
    'simrat39/rust-tools.nvim',
    requires = {
      'nvim-lua/plenary.nvim',
      'neovim/nvim-lspconfig',
    },
  },
  {
    'williamboman/nvim-lsp-installer',
    requires = {
      'neovim/nvim-lspconfig',
      'simrat39/rust-tools.nvim',
      'shurizzle/inlay-hints.nvim',
    },
    name = 'lsp.installer',
  },
  { 'jose-elias-alvarez/null-ls.nvim', name = 'lsp.null-ls' },
  { 'nvim-telescope/telescope-fzf-native.nvim', name = 'telescope.fzf' },
  { 'nvim-telescope/telescope-ui-select.nvim' },
  { 'L3MON4D3/LuaSnip' },
  {
    'saecki/crates.nvim',
    name = 'crates',
    tag = 'v0.1.0',
    requires = { 'nvim-lua/plenary.nvim' },
  },
  { 'hrsh7th/cmp-nvim-lsp' },
  { 'hrsh7th/cmp-buffer' },
  { 'hrsh7th/cmp-path' },
  { 'hrsh7th/cmp-calc' },
  { 'hrsh7th/cmp-emoji' },
  { 'ray-x/cmp-treesitter' },
  { 'lukas-reineke/cmp-rg' },
  {
    'hrsh7th/nvim-cmp',
    name = 'cmp',
    requires = {
      'hrsh7th/cmp-nvim-lsp',
      'hrsh7th/cmp-buffer',
      'hrsh7th/cmp-path',
      'hrsh7th/cmp-calc',
      'hrsh7th/cmp-emoji',
      'ray-x/cmp-treesitter',
      'saecki/crates.nvim',
      'lukas-reineke/cmp-rg',
      'L3MON4D3/LuaSnip',
    },
  },
  {
    'nvim-telescope/telescope.nvim',
    name = 'telescope',
    requires = {
      'nvim-lua/plenary.nvim',
      'kyazdani42/nvim-web-devicons',
      'nvim-telescope/telescope-fzf-native.nvim',
      'nvim-telescope/telescope-ui-select.nvim',
      'rcarriga/nvim-notify',
    },
  },
  { 'arcticicestudio/nord-vim', name = 'nord' },
  { 'arkav/lualine-lsp-progress' },
  {
    'nvim-lualine/lualine.nvim',
    name = 'lualine',
    requires = {
      { 'kyazdani42/nvim-web-devicons', opt = true },
      { 'arkav/lualine-lsp-progress' },
    },
    opt = false,
  },
  {
    'romgrk/barbar.nvim',
    name = 'barbar',
    requires = { 'kyazdani42/nvim-web-devicons', opt = true },
  },
  {
    'kyazdani42/nvim-tree.lua',
    name = 'tree',
    requires = {
      'kyazdani42/nvim-web-devicons',
    },
  },
  { 'nvim-treesitter/nvim-treesitter', name = 'treesitter' },
  { 'norcalli/nvim-colorizer.lua', name = 'colorizer' },
  { 'MarcWeber/vim-addon-local-vimrc' },
  { 'junegunn/goyo.vim' },
  { 'windwp/nvim-autopairs', name = 'autopairs' },
  { 'tpope/vim-repeat' },
  { 'numToStr/Comment.nvim', name = 'comment' },
  { 'tpope/vim-surround' },
  { 'ahmedkhalf/project.nvim', name = 'project' },
  { 'editorconfig/editorconfig-vim' },
  {
    'instant-markdown/vim-instant-markdown',
    disabled = (vim.g.started_by_firenvim or 0) == 0,
  },
  { 'glacambre/firenvim', name = 'firenvim' },
  { 'glepnir/dashboard-nvim', name = 'dashboard' },
}
